import React,{useEffect,useRef,useState} from "react";
import {createRoot} from "react-dom/client";
import "./styles.css";

const PASSWORD="Ashishsaranya";

function Effects({burst=0}){const [bits,setBits]=useState([]);useEffect(()=>{if(!burst)return;setBits(Array.from({length:42},(_,i)=>({id:i,x:Math.random()*100,d:Math.random()*1.2})));const t=setTimeout(()=>setBits([]),2600);return()=>clearTimeout(t)},[burst]);return <>{bits.map(b=><span key={b.id} className="burst" style={{left:b.x+"%",animationDelay:b.d+"s"}}>{["❤️","💗","✨","🌹","💕"][b.id%5]}</span>)}</>}
function Continue({to}){return <a className="continue" href={"#"+to}>Continue ❤️</a>}
function Section({id,children,className=""}){return <section id={id} className={"section "+className}>{children}</section>}

function PasswordScreen({onOpen}){const [v,setV]=useState(""),[bad,setBad]=useState(false);const submit=e=>{e.preventDefault();if(v===PASSWORD)onOpen();else setBad(true)};return <main className="gate"><div className="petals">{Array.from({length:18},(_,i)=><i key={i}>🌹</i>)}</div><div className="gate-card"><div className="big-heart">♥</div><h1>Hey Saranya Babee ❤️</h1><p>This little place is only for you…</p><p>Because there’s something I really want to tell you.</p><form onSubmit={submit}><label>Enter our secret password ❤️</label><input aria-label="Secret password" type="password" value={v} onChange={e=>{setV(e.target.value);setBad(false)}} autoComplete="off"/><button className="primary">Open My Heart ❤️</button></form>{bad&&<div className="error">Oops babee… that’s not our secret password 🥺❤️ Try again.</div>}</div></main>}

function Apology(){return <Section id="apology"><div className="eyebrow">FROM MY HEART</div><h2>I’m Sorry Saranya Babee ❤️</h2><p className="lead">I made this little place just for you.</p><article className="glass letter reveal"><p>Babee,</p><p>I may not always say the right things or do everything perfectly, but one thing I know for sure is that I love you. ❤️</p><p>I’m sorry for whatever I did that hurt your heart.</p><p>If I could take that moment back, I would.</p><p>You mean so much more to me than my ego, my anger, or any silly misunderstanding.</p><p>I don’t want to win an argument.</p><p>I want to win your smile back.</p><p>So today, I’m putting my heart in front of you and simply saying…</p><p className="strong">I’m SORRY, Saranya Babee. ❤️</p></article><Continue to="forgive"/></Section>}

function Forgiveness(){const [ok,setOk]=useState(false),[burst,setBurst]=useState(0);const yes=()=>{setOk(true);setBurst(x=>x+1)};return <Section id="forgive" className="soft"><Effects burst={burst}/><div className="eyebrow">ONE LITTLE ASK</div><h2>Can your idiot get one more chance? 🥺❤️</h2><p className="lead">Will you forgive me, Saranya?</p>{!ok?<div className="choices"><button onClick={yes}>YES ❤️</button><button onClick={yes}>YES, OF COURSE 🥺❤️</button></div>:<div className="celebrate"><h3>I KNEW MY BABEE WOULD FORGIVE ME ❤️🥹</h3><p>Come here… I owe you the biggest hug. 🤗❤️</p><Continue to="heart"/></div>}</Section>}

function HeartInteraction(){const [n,setN]=useState(0),[burst,setBurst]=useState(0);const tap=()=>{setN(x=>x+1);setBurst(x=>x+1);if(navigator.vibrate)navigator.vibrate(25)};return <Section id="heart"><Effects burst={burst}/><div className="eyebrow">A LITTLE GAME</div><h2>Tap My Heart ❤️</h2><button className="tap-heart" onClick={tap} aria-label="Tap my heart"><span>♥</span></button><div className="counter">{n} heart taps</div>{n>=5&&<div className="heart-reveal">See? Even my heart gets excited when you touch it. ❤️<br/><small>Every beat is for you, babee.</small></div>}<Continue to="reasons"/></Section>}

const reasons=[["Your Smile ❤️","Your smile can fix my worst days."],["Your Heart ❤️","Your beautiful heart is one of the reasons I fell for you."],["Your Care 🥺","The way you care about me means more than I can explain."],["Your Presence ❤️","Everything feels a little better when you’re around."],["Simply You ❤️","I don’t need a reason. I love you because you’re you."]];
function Reasons(){const [open,setOpen]=useState(null);return <Section id="reasons" className="soft"><div className="eyebrow">FIVE LITTLE REASONS</div><h2>Reasons Why I Love You ❤️</h2><div className="cards">{reasons.map((r,i)=><button className={"reason "+(open===i?"opened":"")} key={r[0]} onClick={()=>setOpen(open===i?null:i)}><b>{r[0]}</b><span>{open===i?r[1]:"Tap to reveal ❤️"}</span></button>)}</div><Continue to="letters"/></Section>}

const letters=["If I had to choose you again, I would choose you every single time. ❤️","I’m sorry for hurting you. Your smile means more to me than you know. 🥺❤️","I don’t want perfect days. I just want you beside me through all the days.","No matter how many times life gives me the choice, I’ll choose you."];
function LoveLetters(){const [open,setOpen]=useState(null);return <Section id="letters"><div className="eyebrow">WORDS I WANT YOU TO KEEP</div><h2>Open My Little Love Letters 💌</h2><div className="envelopes">{letters.map((x,i)=><button key={i} className={"envelope "+(open===i?"open":"")} onClick={()=>setOpen(open===i?null:i)}><span className="env-top">💌</span><b>{open===i?x:"Open me 💌"}</b></button>)}</div><Continue to="memories"/></Section>}

const memories=[
  ["/photos/photo1.png","Our smiles ❤️"],
  ["/photos/photo2.jpg","My favorite person."],
  ["/photos/photo3.jpg","Us."],
  ["/photos/photo4.jpg","One of my favorite memories."],
  ["/photos/photo5.jpg","Forever with you."],
  ["/photos/photo6.jpg","Just us. ❤️"]
];
function Memories(){return <Section id="memories" className="soft"><div className="eyebrow">THE MOMENTS I KEEP</div><h2>Our Memories ❤️</h2><p className="hint">A few of my favorite moments with you, kept right here. ❤️</p><div className="photos">{memories.map((m,i)=><figure className="polaroid" key={i}><div className="photo-frame"><img src={m[0]} alt={`Memory ${i+1} with Saranya`} loading="lazy"/></div><figcaption>{m[1]}</figcaption></figure>)}</div><Continue to="promise"/></Section>}
function Promise(){const [open,setOpen]=useState(false);return <Section id="promise"><div className="eyebrow">FROM ME TO YOU</div><h2>A Little Promise From Me ❤️</h2><button className={"promise "+(open?"opened":"")} onClick={()=>setOpen(!open)}><b>{open?"I promise…":"Tap to open…"}</b>{open&&<div><p>To communicate instead of staying angry.</p><p>To listen to you.</p><p>To understand you.</p><p>To protect what we have.</p><p>To make you smile.</p><p>To keep choosing you.</p><p>Again and again.</p><p>Every single day. ❤️</p></div>}</button><Continue to="surprise"/></Section>}

function Surprise(){const [open,setOpen]=useState(false);return <Section id="surprise" className="soft"><div className="eyebrow">CHEESY WARNING</div><h2>One Last Little Surprise 🎁</h2><p className="lead">Don’t open this unless you’re ready for something cheesy…</p><button className={"gift "+(open?"opened":"")} onClick={()=>setOpen(!open)}><span className="lid">🎀</span><span className="box">🎁</span></button>{open&&<div className="surprise"><h3>Surprise! ❤️</h3><p>You’re stuck with me forever. 😌</p><p>No refunds.<br/>No exchanges.<br/>Lifetime subscription. 💍❤️</p></div>}<Continue to="proposal"/></Section>}

function Proposal(){const [yes,setYes]=useState(false),[burst,setBurst]=useState(0);const choose=()=>{setYes(true);setBurst(x=>x+1)};return <Section id="proposal" className="proposal"><Effects burst={burst}/><div className="stars">✦　·　✧　·　✦　·　⋆　·　✧</div>{!yes?<><div className="proposal-heart">♥</div><div className="eyebrow">JUST ONE MORE THING</div><h2>Okay Saranya Babee…</h2><p className="lead">One more question…</p><h1 className="question">Will you marry me? 💍❤️</h1><div className="choices"><button onClick={choose}>YES ❤️</button><button onClick={choose}>YESSSS BABEE 💍❤️</button></div></>:<div className="yes-screen"><div className="ring">💍</div><div className="proposal-heart">♥</div><h1>SHE SAID YESSSS! 💍❤️🥹</h1><p>Looks like I’m keeping you forever, babee.</p><p>Forever sounds pretty good with you. ❤️</p><Continue to="final"/></div>}</Section>}

function Final(){return <Section id="final" className="final"><div className="eyebrow">BEFORE YOU LEAVE…</div><h2>Before you leave…</h2><article className="final-letter"><p>Saranya,</p><p>I’m sorry.<br/>I love you.<br/>I choose you.</p><p>And if you’ll let me…<br/>I want to spend my life making you smile.</p><p>Through the good days.<br/>Through the bad days.<br/>Through every silly fight.<br/>Through every laugh.<br/>Through every crazy moment.</p><p>I want us.</p><p>Forever.</p><p>Love,<br/>Ashish ❤️</p></article><h1>I Love You, Saranya Babee ❤️</h1><p className="always">Always. ❤️</p><div className="final-heart">♥</div></Section>}

function Music(){const ref=useRef(null),[playing,setPlaying]=useState(false),[available,setAvailable]=useState(true);useEffect(()=>{const a=ref.current;const err=()=>setAvailable(false);a?.addEventListener("error",err);return()=>a?.removeEventListener("error",err)},[]);const toggle=async()=>{if(!available)return;try{if(playing)await ref.current.pause();else await ref.current.play();setPlaying(!playing)}catch{}};return <><audio ref={ref} src="/our-song.mp3" loop preload="none"/><button className="music" onClick={toggle}>{playing?"⏸️ Pause":"🎵 Our Song"}</button></>}

function App(){const [open,setOpen]=useState(false);useEffect(()=>{if(open){document.documentElement.style.scrollBehavior="smooth";}return()=>{document.documentElement.style.scrollBehavior=""}},[open]);return open?<><Music/><div className="app"><Apology/><Forgiveness/><HeartInteraction/><Reasons/><LoveLetters/><Memories/><Promise/><Surprise/><Proposal/><Final/></div></>:<PasswordScreen onOpen={()=>setOpen(true)}/>}

createRoot(document.getElementById("root")).render(<App/>);
